// WordPress webpack config.
const defaultConfig = require( '@wordpress/scripts/config/webpack.config' );

// Plugins.
const RemoveEmptyScriptsPlugin = require( 'webpack-remove-empty-scripts' );
const BrowserSyncPlugin = require( 'browser-sync-webpack-plugin' )

// Utilities.
const path = require( 'path' );

// Add any new entry points by extending the webpack config.
module.exports = {
	...defaultConfig,
	...{
		entry: {
			'js/screen': path.resolve( process.cwd(), 'src/js', 'screen.js' ),
			'js/editor': path.resolve( process.cwd(), 'src/js', 'editor.js' ),
			'css/screen': path.resolve( process.cwd(), 'src/scss', 'screen.scss' ),
			'css/editor': path.resolve( process.cwd(), 'src/scss', 'editor.scss' ),
			'css/theme-info': path.resolve( process.cwd(), 'src/scss', 'theme-info.scss' ),
		},
		plugins: [
			// Include WP's plugin config.
			...defaultConfig.plugins,

			// Removes the empty `.js` files generated by webpack but
			// sets it after WP has generated its `*.asset.php` file.
			new RemoveEmptyScriptsPlugin( {
				stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS
			} ),

			new BrowserSyncPlugin(
				// BrowserSync options
				{
					// browse to http://localhost:3000/ during development
					host: 'localhost',
					port: 3000,

					// proxy the Webpack Dev Server endpoint
					// (which should be serving on http://wordpress.local/)
					// through BrowserSync
					proxy: 'http://wordpress.local/',

					// Stop the browser from automatically opening
					open: false,

					// Don't show any notifications in the browser.
					notify: false,
				}
			)
		]
	}
};
